name: CI

on: [push, pull_request]

jobs:

  check:

    if: github.ref_type == 'branch' && github.event_name == 'push' && github.ref_name != 'main'
    name: Run checks
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        id: checkout-repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Java
        id: install-java
        run: make install-check-java

      - name: Install Pip
        id: install-pip
        run: make install-pip

      - name: Install Poetry
        id: install-poetry
        run: make install-poetry

      - name: Install dependencies
        id: install-dependencies
        run: make install-all

      - name: Run checks
        id: run-checks
        run: make check

  ci:

    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    name: Run Checks on '${{ matrix.os }}' with '${{ matrix.python-version }}'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
      fail-fast: false
      max-parallel: 15

    steps:

      - name: Checkout repository
        id: checkout-repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Java
        id: install-java
        run: make install-check-java

      - name: Install Pip
        id: install-pip
        run: make install-pip

      - name: Install Poetry
        id: install-poetry
        run: make install-poetry

      - name: Install dependencies
        id: install-dependencies
        run: make install-all

      - name: Run checks
        id: run-checks
        run: make check
