name: CI

on: [push, pull_request]

jobs:

  check:

    if: github.ref_type == 'branch' && github.event_name == 'push' && github.ref_name != 'main'
    name: Run checks
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        id: checkout-repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Java
        id: install-java
        run: make install-check-java

      - name: Install Pip
        id: install-pip
        run: make install-pip

      - name: Install Poetry
        id: install-poetry
        run: make install-poetry

      - name: Install dependencies
        id: install-dependencies
        run: make install-all

      - name: Run checks
        id: run-checks
        run: make check

  ci:

    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    name: Run Checks on '${{ matrix.os }}' with '${{ matrix.python-version }}'

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
      fail-fast: false
      max-parallel: 15

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout repository
        id: checkout-repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Java
        id: install-java
        # if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true

      - name: Upgrade Pip
        id: upgrade-pip
        run: make upgrade-pip

      - name: Install Poetry
        id: install-poetry
        run: make install-poetry

      - name: Install dependencies
        id: install-dependencies
        run: make install-all

      - name: Check .venv setup on ${{ matrix.os }}
        id: check-venv-not-windows
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        run: |
          echo "ls -la:"
          ls -la
          echo "ls -la .venv:"
          ls -la .venv
          echo "ls -la .venv/bin:"
          ls -la .venv/bin
          echo "ls -la .venv/lib:"
          ls -la .venv/lib

      - name: Check .venv setup on ${{ matrix.os }}
        id: check-venv-windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          echo "dir:"
          dir
          echo "dir .venv:"
          dir .venv
          echo "dir .venv\Scripts:"
          dir .venv\Scripts
          echo "dir .venv\Lib:"
          dir .venv\Lib

      - name: Run checks
        id: run-checks
        run: make check
